<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Roamly.Api\Roamly.Api.csproj" />
    <ProjectReference Include="..\..\src\Roamly.Infrastructure\Roamly.Infrastructure.csproj" />
    <ProjectReference Include="..\Roamly.TestSupport\Roamly.TestSupport.csproj" />
  </ItemGroup>
</Project>
