// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roamly.Infrastructure.Persistence;

#nullable disable

namespace Roamly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RoamlyDbContext))]
    [Migration("20260928095239_InitialPhase1")]
    partial class InitialPhase1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Roamly.Domain.Entities.Camper", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AverageConsumptionLPer100Km")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Brand")
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte?>("FuelKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Model")
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("VehicleKind")
                        .HasColumnType("tinyint");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Capacities", "Roamly.Domain.Entities.Camper.Capacities#Capacities", b1 =>
                        {
                            b1.Property<int>("FreshWaterL")
                                .HasColumnType("int")
                                .HasColumnName("FreshWaterL");

                            b1.Property<int>("FuelTankL")
                                .HasColumnType("int")
                                .HasColumnName("FuelTankL");

                            b1.Property<int>("GasKg")
                                .HasColumnType("int")
                                .HasColumnName("GasKg");

                            b1.Property<int>("GreyWaterL")
                                .HasColumnType("int")
                                .HasColumnName("GreyWaterL");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dimensions", "Roamly.Domain.Entities.Camper.Dimensions#Dimensions", b1 =>
                        {
                            b1.Property<int>("HeightMm")
                                .HasColumnType("int")
                                .HasColumnName("HeightMm");

                            b1.Property<int>("LengthMm")
                                .HasColumnType("int")
                                .HasColumnName("LengthMm");

                            b1.Property<int>("WidthMm")
                                .HasColumnType("int")
                                .HasColumnName("WidthMm");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Weights", "Roamly.Domain.Entities.Camper.Weights#Weights", b1 =>
                        {
                            b1.Property<int>("KerbWeightKg")
                                .HasColumnType("int")
                                .HasColumnName("KerbWeightKg");

                            b1.Property<int>("MaxWeightKg")
                                .HasColumnType("int")
                                .HasColumnName("MaxWeightKg");
                        });

                    b.HasKey("OwnerId", "Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("OwnerId", "Id"));

                    b.ToTable("Campers");
                });

            modelBuilder.Entity("Roamly.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CamperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateOnly?>("InstalledOnUtc")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("OwnerId", "Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("OwnerId", "Id"));

                    b.HasIndex("OwnerId", "CamperId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Roamly.Domain.Entities.ErasureReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeletedRowCounts")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErasedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("StorageSweepConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SubjectHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("ErasureReceipts");
                });

            modelBuilder.Entity("Roamly.Domain.Entities.MaintenanceItem", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CamperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("IntervalKm")
                        .HasColumnType("int");

                    b.Property<short?>("IntervalMonths")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("LastServiceOdometerKm")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastServiceOnUtc")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("NextDueOdometerKm")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NextDueOnUtc")
                        .HasColumnType("date");

                    b.Property<byte>("Origin")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SeedCatalogVersion")
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SeedTemplateKey")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("OwnerId", "Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("OwnerId", "Id"));

                    b.HasIndex("OwnerId", "CamperId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("OwnerId", "CamperId"), new[] { "NextDueOnUtc", "NextDueOdometerKm" });

                    b.HasIndex("OwnerId", "NextDueOnUtc")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("MaintenanceItems", t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceItem_IntervalKm", "[IntervalKm] IS NULL OR [IntervalKm] >= 1");

                            t.HasCheckConstraint("CK_MaintenanceItem_IntervalMonths", "[IntervalMonths] IS NULL OR [IntervalMonths] >= 1");

                            t.HasCheckConstraint("CK_MaintenanceItem_Recurrence", "[IntervalKm] IS NOT NULL OR [IntervalMonths] IS NOT NULL");

                            t.HasCheckConstraint("CK_MaintenanceItem_SeedProvenance", "([Origin] = 1 AND [SeedTemplateKey] IS NOT NULL) OR ([Origin] = 0 AND [SeedTemplateKey] IS NULL)");
                        });
                });

            modelBuilder.Entity("Roamly.Domain.Entities.MaintenanceLog", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("MaintenanceItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("OdometerKm")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PerformedOnUtc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Workshop")
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cost", "Roamly.Domain.Entities.MaintenanceLog.Cost#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("CostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasColumnName("CostCurrency");
                        });

                    b.HasKey("OwnerId", "Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("OwnerId", "Id"));

                    b.HasIndex("OwnerId", "MaintenanceItemId", "PerformedOnUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("MaintenanceLogs", t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceLog_CostCurrency", "[CostCurrency] IS NULL OR ([CostCurrency] = UPPER([CostCurrency]) AND LEN([CostCurrency]) = 3)");
                        });
                });

            modelBuilder.Entity("Roamly.Domain.Entities.OdometerReading", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CamperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("ReadingKm")
                        .HasColumnType("int");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("TakenOnUtc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("OwnerId", "Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("OwnerId", "Id"));

                    b.HasIndex("OwnerId", "CamperId", "TakenOnUtc")
                        .IsUnique()
                        .IsDescending(false, false, true);

                    b.ToTable("OdometerReadings");
                });

            modelBuilder.Entity("Roamly.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("DeletionRequestedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("DeletionScheduledForUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrivacyPolicyVersionSeen")
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReportingCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("EUR");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeletionScheduledForUtc")
                        .HasFilter("[DeletionScheduledForUtc] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_ReportingCurrency", "[ReportingCurrency] = UPPER([ReportingCurrency]) AND LEN([ReportingCurrency]) = 3");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roamly.Domain.Entities.Camper", b =>
                {
                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Roamly.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Roamly.Domain.Entities.Camper", "Camper")
                        .WithMany("Equipment")
                        .HasForeignKey("OwnerId", "CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("Roamly.Domain.Entities.MaintenanceItem", b =>
                {
                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Roamly.Domain.Entities.Camper", "Camper")
                        .WithMany("MaintenanceItems")
                        .HasForeignKey("OwnerId", "CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("Roamly.Domain.Entities.MaintenanceLog", b =>
                {
                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Roamly.Domain.Entities.MaintenanceItem", "MaintenanceItem")
                        .WithMany("Logs")
                        .HasForeignKey("OwnerId", "MaintenanceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceItem");
                });

            modelBuilder.Entity("Roamly.Domain.Entities.OdometerReading", b =>
                {
                    b.HasOne("Roamly.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Roamly.Domain.Entities.Camper", "Camper")
                        .WithMany("OdometerReadings")
                        .HasForeignKey("OwnerId", "CamperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("Roamly.Domain.Entities.Camper", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("MaintenanceItems");

                    b.Navigation("OdometerReadings");
                });

            modelBuilder.Entity("Roamly.Domain.Entities.MaintenanceItem", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
